### ISSUE TITLE
Client used for viewing Jupyternotebook?

### ISSUE THREAD

**Issue by pgensler** [fastai/numerical-linear-algebra#1]
What type of client are you using in your videos to view your jupyter notebooks? Is that a new version of Jupyter Labs? I have not seen that before, and it looks much cleaner than prior jupyter notebooks I have used. Thanks.

**Comment by racheltho** [comment]
I want to answer questions like this on [our forums](forums.fast.ai), so I've gone ahead and written an answer there: http://forums.fast.ai/t/packages-and-extensions-for-jupyter-notebooks/4149  
Thanks!
