### ISSUE TITLE
Question mark in notebook name causing issues on Windows.

### ISSUE THREAD

**Issue by bkbeckman** [fastai/numerical-linear-algebra#5]
When attempting to clone the repository in Windows 10, I get an error:

```
$ git clone https://github.com/fastai/numerical-linear-algebra.git
Cloning into 'numerical-linear-algebra'...
remote: Counting objects: 300, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 300 (delta 0), reused 2 (delta 0), pack-reused 295
Receiving objects: 100% (300/300), 62.56 MiB | 5.06 MiB/s, done.
Resolving deltas: 100% (97/97), done.
**error: unable to create file nbs/1. Why are we here?.ipynb: Invalid argument**
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

When attempting to download the repository as a zip file using the "clone or download" button in github, the Windows Exporer built-in zip browser does not show notebook one.  **This appears to be caused by the '?' in the file name.**

The work around for this issue it to use a command line zip tool to extract the notebook and rename it.

`$ unzip -p "numerical-linear-algebra-master/nbs/1. Why are we here?.ipynb" > "1. why are we here.ipynb"
`

**Comment by racheltho** [comment]
Thanks for flagging this.  I've renamed the notebook to resolve the issue: https://github.com/fastai/numerical-linear-algebra/commit/974381f7343e82e7491a5a55f61397de4b10a82c
