### ISSUE TITLE
Background model videos used in notebook 3 don't seem to be available any longer

### ISSUE THREAD

**Issue by VishnuSanjay** [fastai/numerical-linear-algebra#9]
http://bmc.iut-auvergne.com/?author=1

This is the site I was redirected to by the link at the top of notebook 3. Is there another known source for the two videos used in the notebook?

I refer to notebook 3 in the 2017 version of the course.

**Comment by ejulio** [comment]
Hey @VishnuSanjay, I was at the same situation as you.
I searched for alternatives and I found http://www.scenebackgroundmodeling.net/.
There is the video PETS2006 from the basic section that has the same properties (static camera) we want.

**Comment by indrajitsg** [comment]
This is really irritating - the entire website is gone it seems. Fast.ai should do a better job of storing and sharing their datasets.

**Comment by petulla** [comment]
Ymmv but there are archived snapshots of that blog on Archive.org https://web.archive.org/web/20170706161546/http://bmc.iut-auvergne.com/?author=1

**Comment by ostaski** [comment]
I found the BMC 2012 dataset here on github at [https://github.com/momonala/image-processing-projects/tree/master/background_removal/video/Video_003](https://github.com/momonala/image-processing-projects/tree/master/background_removal/video/Video_003)

**Comment by la-tuna** [comment]
Hi, as the data of PETS2006 seem to be unreachable on the official website, I am wondering if you still have them. If you have a backup, could you please share them through a copy on Drive or Dropbox ? Thank you

> Hey [@VishnuSanjay](https://github.com/VishnuSanjay), I was at the same situation as you. I searched for alternatives and I found http://www.scenebackgroundmodeling.net/. There is the video PETS2006 from the basic section that has the same properties (static camera) we want.
